### ISSUE TITLE
Feat: Search Component

### ISSUE THREAD

**Issue by sumin10** [sumin10/nyt-search#1]
## 개요
nyt-search component 생성

## TODO LIST
- [ ] 0.5초 동안 추가 입력 없이 input value가 있는 경우 검색 api 호출
- [ ] 최대 5개 history 저장
- [ ] history가 있을 시, input에 focus중이면 노출
